# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: main_config
    configs:
        main_config:
            local: 'fr'
            language: fr
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', '-', 'Styles', 'Format', '-', 'TextColor', 'BGColor', 'Source'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
        offer:
            local: 'fr'
            language: fr
            toolbar:
                - { name: "styles", items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Blockquote','RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Styles', 'Format', '-', 'TextColor', 'BGColor', 'Source' ] }