vich_uploader:
    db_driver: orm
    twig: true
    form: true

    mappings:
        user_image:
            uri_prefix: /data/img/user
            upload_destination: '%kernel.project_dir%/public/data/img/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
